### ISSUE TITLE
[Feature Request] New Commands - Pin/Unpin Sidebars

### ISSUE THREAD

**Issue by FelipeRearden** [0phoff/obsidian-sidetogglecmd#1]
Hello @0phoff !!!!

My FR is simple to explain: would be amazing if we could have commands for PIN and UNPIN the sidebars :)

These are the commands
- [ ] Pin Left Sidebar
- [ ] Unpin Left Sidebar
- [ ] Toggle Pin/unpin on Left Sidebar
- [ ] Pin Right Sidebar
- [ ] Unpin Right Sidebar
- [ ] Toggle Pin/unpin on Right Sidebar

### My Workflow

I have a specific workflow where I have to use the Left Sidebar Pinned with the Search Core Plug-in 

I have a command that opens this workspace with a hotkey 

I use the QuickAdd plug-in to merge these commands into a single command.

The only thing that I miss is a command to Pin the left sidebar :(

Unfortunately Workspaces core plug-in doesn’t save the sidebar pin/unpin status :

---

Thanks for reading this

Have a great day!!!

**Comment by 0phoff** [comment]
What exactly do you mean with "pinning" a sidebar ?
I know you can pin a tab window, but that doesn't make sense for the sidebar ?

**Comment by FelipeRearden** [comment]
> What exactly do you mean with "pinning" a sidebar ?
> I know you can pin a tab window, but that doesn't make sense for the sidebar ?

There is an icon on each Sidebar that Pin/Unpin the Sidebar on Obsidian window 

📸
![AE755028-00D3-4562-9306-9BEC6E91FA79](https://user-images.githubusercontent.com/85180696/202452344-2266cac6-7bd1-4378-a435-39dc19d957fd.jpeg)

If a Sidebar is **Pinned** it will behaves as a note . In other words it will steal space in the window (as you can see in the image above)

MY FR is about creating a command to be able to change the set of behaviors related to this topic with a hotkey. 

---

Thanks for your reply, let me know if you need more information !

Have  a great day!!!!

**Comment by 0phoff** [comment]
Hmm, I don't seem to have that button.

Could you check which version of Obsidian you have and what plugins you have ?
It might be a plugin is adding this behaviour.

**Comment by FelipeRearden** [comment]
> Hmm, I don't seem to have that button.
> 
> Could you check which version of Obsidian you have and what plugins you have ? It might be a plugin is adding this behaviour.

I checked under a new installation with zero plugins under Obsidian v1.03 

→ It's inside .workspace.drawer-header

📸 I took these screenshots to try to help (forgive for the bad quality)
![18E68F75-B775-46D9-870D-DCDEFF63E145](https://user-images.githubusercontent.com/85180696/202693868-6e0b9ed4-25f6-4481-abb9-8461ff2dfca5.jpeg)
![3E24DB72-017B-4DDA-B186-FC5BD2E37AF0](https://user-images.githubusercontent.com/85180696/202693909-b5a5fc08-4dfd-4eb7-9e51-084fe2484b8e.jpeg)



---

Let me know if you need more info :)

**Comment by FelipeRearden** [comment]
@0phoff I find out what is happening. 

Before version v.1.x the sidebars could be pinned/unpinned the way that I described above. 
→ On Desktop and on Mobile

After v.1.x this feature is only available on Mobile (that why you are not seeing on Desktop) 
→ For some reason they change this behavior 

Forgive me for not seeing this upfront. I am investing time to mirror Obsidian on Mobile (iPad with mouse and keyboard) with Desktop that I forgot to check on mobile 

---

Feel free to close this issue. With you want to bring this feature to mobile, you can transform your Desktop vault into mobile  by running this command on Console 

From Discord: You can toggle mobile emulation on your desktop by entering this in the console:

```
this.app.emulateMobile(!this.app.isMobile)
```
